default_agent: test1
agents:
  test:
    name: test
    language: python
    node_version: '20'
    entrypoint: C:/Users/maraf/BIGB/Project/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\maraf\BIGB\Project
    aws:
      execution_role: arn:aws:iam::423781074828:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-9f86d08188
      execution_role_auto_create: false
      account: '423781074828'
      region: ap-south-1
      ecr_repository: 423781074828.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-test
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-test-builder
      execution_role: arn:aws:iam::423781074828:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-9f86d08188
      source_bucket: bedrock-agentcore-codebuild-sources-423781074828-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  test1:
    name: test1
    language: python
    node_version: '20'
    entrypoint: C:/Users/maraf/BIGB/Project/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\maraf\BIGB\Project
    aws:
      execution_role: arn:aws:iam::423781074828:role/AmazonBedrockAgentCoreSDKRuntime-ap-south-1-1b4f0e9851
      execution_role_auto_create: false
      account: '423781074828'
      region: ap-south-1
      ecr_repository: 423781074828.dkr.ecr.ap-south-1.amazonaws.com/bedrock-agentcore-test1
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: test1-HBDXfJ46Xa
      agent_arn: arn:aws:bedrock-agentcore:ap-south-1:423781074828:runtime/test1-HBDXfJ46Xa
      agent_session_id: f20eb12a-130f-4560-bfc9-67ef8f307f11
    codebuild:
      project_name: bedrock-agentcore-test1-builder
      execution_role: arn:aws:iam::423781074828:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-south-1-1b4f0e9851
      source_bucket: bedrock-agentcore-codebuild-sources-423781074828-ap-south-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
